#! /bin/bash

# colors for echo output
RED='\033[0;31m'
NC='\033[0m' # No Color

# print error function
print_need_tool() {
	echo -e "${RED}ERROR: we need $1 installed to compile.${NC}"
	exit 1
}

# check that java, scala and sbt are installed
if [[ $(which java) == "" ]]; then
	print_need_tool "java"
fi

if [[ $(which sbt) == "" ]]; then
	print_need_tool "sbt"
fi


# compile using sbt
echo -e "Building the executable"
sbt clean
sbt pack

# create a symbolic link file in the root directory
rm -f repetita
ln -s target/pack/bin/repetita repetita
chmod +x repetita

# generate doc. If everything is ok, notify the user.
bash repetita -doc && echo -e "\nGood news! Basic functions seem to work: You can already run ./repetita\nTry, for example: $ ./repetita -graph data/2016TopologyZooUCL_inverseCapacity/Abilene.graph -demands data/2016TopologyZooUCL_inverseCapacity/Abilene.0000.demands -solver defoCP -t 1 -scenario SingleSolverRun\n"

